[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
caller = "FADPYpQH3DnQtX5YNsZ9p4omK16CuDGxZDdiK5Tmkgbw"
callee = "HrMvp3czrxbvkkNzvpHrTwA6hS9S8LNJgLcuZ9Qnzc9x"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
